name: Testing
on:
  push:
    branches: ["*"]
    tags-ignore: ["*"]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: ~

jobs:
  test:
    name: Tests and style checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install '.[dev]'
          python -m pip install -e .
      - name: Lint
        run: |
          flake8 problemdetails tests.py
      - name: Check format
        run: |
          yapf -dr problemdetails tests.py
      - name: Run tests
        run: |
          coverage run -m pytest tests.py
          coverage report
          coverage xml -o ./build/coverage.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v1.3.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./build/coverage.xml
          flags: unittests
          fail_ci_if_error: true
